on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n aksdocker -g aksdockerb5b5-rg --location "East US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n aksdocker --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n aksdocker --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n aksdocker --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: aksdocker.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/06-todo-rest-api-h2-containerized" -f  "06-todo-rest-api-h2-containerized/Dockerfile" -t aksdocker.azurecr.io/aksdevtestfree:${{ github.sha }} --label dockerfile-path=06-todo-rest-api-h2-containerized/Dockerfile
        docker push aksdocker.azurecr.io/aksdevtestfree:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_aksdevtestfree_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep springboot | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace springboot`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: springboot
        container-registry-url: aksdocker.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: aksdevtestfrdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: springboot
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          aksdocker.azurecr.io/aksdevtestfree:${{ github.sha }}
        imagepullsecrets: |
          aksdevtestfrdockerauth   
